
server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&useAffectedRows=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    mapper-locations: classpath*:com/ww/mapper/*Mapper.xml
    type-aliases-package: com.ww.mapper
    configLocation: classpath:mybatis-config.xml
  redis:
    host: 127.0.0.1
    #redis密码，没有密码的可以用～表示
    password: ~
    port: 6379
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000


