server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081

spring:
  application:
    name: SpringbootProject

  # 当前maven打包的profile
  profiles:
    active: @profileActive@

  # UTF-8编码
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

  # mysql数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&useAffectedRows=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  # mybatis配置
  mybatis:
    mapper-locations: classpath*:com/ww/mapper/*Mapper.xml
    type-aliases-package: com.ww.mapper
    configLocation: classpath:mybatis-config.xml

  # redis配置
  redis:
    host: 127.0.0.1
    #redis密码，没有密码的可以用～表示
    password: ~
    port: 6379
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000


